name: Deploy

on: 
  push:
    branches:
    - uat

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: 'AKIAZQSXQGB4O4LICDNC'
          aws-secret-access-key: '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'
          aws-region: ap-south-1
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          zip -j deploy.zip ./../Lambda-ci/*
          aws lambda update-function-code --function-name=arn:aws:lambda:ap-south-1:654092284024:function:abc --zip-file=fileb://deploy.zip

